# ============================================================
# Cloud Inventory Pro - Configuraci\u00f3n principal
# ============================================================
spring.application.name=cloud-inventory-pro
server.port=8080

# ============================================================
# Base de datos MySQL
# ============================================================
spring.datasource.url=jdbc:mysql://localhost:3306/cloud_inventory_pro?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================================
# JPA / Hibernate
# ============================================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ============================================================
# Logs
# ============================================================
logging.level.com.cloudinventory=DEBUG
logging.level.org.springframework.security=DEBUG